### ISSUE TITLE
CLI tool failing on FreeBSD

### ISSUE THREAD

**Issue by duncan-bayne** [arachnys/athenapdf#100]
After installing athendapdf with `docker pull arachnysdocker/athenapdf`, I tried to convert an HTML file called `review.html` to PDF.

This fails as follows:

```
$ docker run --rm -v $(pwd):/converted/ arachnysdocker/athenapdf athenapdf ./review.html .
[89390:0405/141456.780648:FATAL:zygote_host_impl_linux.cc(140)] Check failed: base::UnixDomainSocket::EnableReceiveProcessId(fds[0]).
#0 0x000001ccd51e <unknown>
#1 0x000001cb27cb <unknown>
#2 0x000002c6126b <unknown>
#3 0x000002bfa64f <unknown>
#4 0x000002ad1f4e <unknown>
#5 0x000002991d2c <unknown>
#6 0x0000029e36ef <unknown>
#7 0x000002989128 <unknown>
#8 0x0000026d99e4 <unknown>
#9 0x0000026d9df0 <unknown>
#10 0x000003b85483 main
#11 0x000811021b45 <unknown>
#12 0x0000005a9009 <unknown>

jail: /athenapdf/entrypoint.sh athenapdf ./review.html .: exited on signal 6
```

My system details are:

```
$ docker --version
Docker version 1.7.0-dev, build 582db78
$ uname -a
FreeBSD x220 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by MrSaints** [comment]
Thanks for reporting this. Seems like a Chromium + Docker + FreeBSD problem. For now, it might help to use a different OS.

**Comment by duncan-bayne** [comment]
@MrSaints Thanks for replying so promptly :)  I'm currently using wkhtmltopdf, so there's no rush for now, I'll carry on with that.

In the meantime I'm very happy to help out with debugging the problem, if I can, by running debug builds, sending logs, etc.

**Comment by MrSaints** [comment]
@duncan-bayne I appreciate your huge support 😄 I'll look into it, and get back to you. In the meantime, if you could try running the CLI without Docker, that'd be great.

**Comment by MrSaints** [comment]
Sorry I haven't been able to test this out on a machine with FreeBSD, but if you ever run into this again, and if you have some spare time, give the new version a shot:

```
docker run --rm -v $(pwd):/conversions/ arachnysdocker/athenapdf:3
```

I'd love to see if it is still a problem! 😄

**Comment by duncan-bayne** [comment]
@MrSaints Thanks - I'll give this a whirl shortly (just upgraded to FreeBSD 11.1) and will let you know how I get on.

**Comment by duncan-bayne** [comment]
Ended up sticking with wkhtmltopdf; please feel free to close this issue if you'd like.
