### ISSUE TITLE
SignatureDoesNotMatch with weaver to s3

### ISSUE THREAD

**Issue by gleclaire** [arachnys/athenapdf#101]
I am getting the following when I try request weaver upload to the pdf to S3

Error #01: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
mfpdf_service_1  |      status code: 403, request id: 423990AD92B37E16, host id: DfNwssdCx3PTB2Dv6x2DmYP2xzlGWWAaV/NK5wUJglenz8mGFqb6QnA1L//E8iZA2G078HO0p9w=

the credentials, bucket, and key combination work with other tools such as Cyberduck and minio client.

**Comment by MrSaints** [comment]
Can you supply the request you are using (with the credentials omitted of course)?

**Comment by gleclaire** [comment]
turns out that the url encoding on postman is not working correctly.  This meant that the AWS_SECRET was incorrect.

Great package.

**Comment by MrSaints** [comment]
Cheers @gleclaire.
