### ISSUE TITLE
Example conversion breaks

### ISSUE THREAD

**Issue by gypsydave5** [arachnys/athenapdf#107]
I was just playing around with Weaver locally and the example conversion used in the Readme (of http://blog.arachnys.com/) causes the renderer process to crash:

```
weaver_1  | [AthenaPDF] converting to PDF: http://blog.arachnys.com/
weaver_1  | captured errors:
weaver_1  | Error #01: exit status 1 : Xlib:  extension "RANDR" missing on display ":99".
weaver_1  | Xlib:  extension "RANDR" missing on display ":99".
weaver_1  | libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
weaver_1  | The renderer process has crashed.
```

Worked for everything else I threw at it though! 😄 

Docker version:
Version 17.05.0-ce-mac11 (17656)
Channel: edge
ffbc5f5871

**Comment by MrSaints** [comment]
Thanks for reporting this.

Duplicate of #95.
