### ISSUE TITLE
Weaver executes request twice

### ISSUE THREAD

**Issue by borkdude** [arachnys/athenapdf#108]
To reproduce:

    echo "Test" > index.html
    python -m SimpleHTTPServer 8090
    
In another terminal:

    docker run -p 8080:8080 --rm --security-opt seccomp:unconfined --shm-size="2g" --env WEAVER_ATHENA_CMD="athenapdf -S -D 1000" arachnysdocker/athenapdf-service

Make the request to Weaver (fill in host IP):

    http://localhost:8080/convert?auth=arachnys-weaver&url=http://<host ip>:8090/index.html

In the Python webserver logs:

    10.0.1.2 - - [05/Jun/2017 18:17:29] "GET /index.html HTTP/1.1" 200 -
    10.0.1.2 - - [05/Jun/2017 18:17:31] "GET /index.html HTTP/1.1" 200 -

**Comment by MrSaints** [comment]
Thanks for filing an issue, but this is a duplicate of https://github.com/arachnys/athenapdf/issues/53.
