### ISSUE TITLE
javascript-delay and/or window-status

### ISSUE THREAD

**Issue by borkdude** [arachnys/athenapdf#113]
As AthenaPDF is a drop in replacement for wkhtml2pdf, I'm looking for either `javascript-delay` or `window-status` so my website can indicate when it's ready to AthenaPDF. Are these implemented or are there any plans for it?

**Comment by MrSaints** [comment]
You can set a delay using `-D`. Use the `--help` flag for more information.

**Comment by borkdude** [comment]
@MrSaints We're currently using the fixed time limit (which is similar to javascript-delay). wkhtml2pdf also offers the option of setting the window status to signal the browser that the PDF can be generated. From the docs:

```
 --window-status <windowStatus>  Wait until window.status is equal to this
                                      string before rendering page
```

This feature would be more helpful to us. Are there any plans for implementing it?

**Comment by MrSaints** [comment]
That feature is not currently available. I'll make a note of it for version 3.

**Comment by MrSaints** [comment]
It is now resolved in version 3.

**Comment by borkdude** [comment]
@MrSaints Is this already available when using the AthenaPDF service Docker? I'm unsure how I should invoke it.

**Comment by MrSaints** [comment]
@borkdude I just rolled out a new service assembly yesterday, so it is not currently on Docker Hub. It is available on the CLI assembly. Is the former something you'd be interested in?

**Comment by borkdude** [comment]
We currently use the service, but it'd be good to know how to call the CLI, because we need to configure it in the future anyway.
Currently I'm trying this and I'm not getting 3 to work at all:
```
docker run --rm -v $(pwd):/converted/ arachnysdocker/athenapdf:3 athenapdf https://www.nu.nl
2017/07/25 10:52:29 Unable to contact debugger at http://localhost:36577/json after 15 seconds, gave up
```

**Comment by MrSaints** [comment]
@borkdude I see. I've updated the CLI v3 image on Docker Hub. It should work as expected now (fixes #119). See the shell script wrapper https://github.com/arachnys/athenapdf/blob/v3/bin/athenapdf.sh for an example of how you can call it via Docker.

**Comment by borkdude** [comment]
@MrSaints I might be doing something wrong, but after the pull of the most recent image I get this:

```
docker run --rm -v $(pwd):/converted/ arachnysdocker/athenapdf:3 athenapdf https://www.google.com
athenapdf: error: failed to load the page: net::ERR_FILE_NOT_FOUND
```

**Comment by MrSaints** [comment]
Try `docker run --rm -v $(pwd):/conversions/ arachnysdocker/athenapdf:3 <URL>` instead.

**Comment by bersling** [comment]
How can I use this flag when I'm using athenapdf as a microservice? More generally, how can I pass options to an athena microservice?

I'm starting the microservice like this: `docker run -p 8080:8080 --rm arachnysdocker/athenapdf-service`.  Do I need to pass this flag here? Or do I need to pass the flag during the request, i.e. somewhere here `curl http://localhost:8080/convert\\?auth\\=arachnys-weaver\\&url\\=${url} > ${outPath}`, maybe as a query param or as a payload?

**Comment by POD666** [comment]
Try this:
`curl http://localhost:8080/convert\\?auth\\=arachnys-weaver\\&waitForStatus&url\\=${url} > ${outPath}`
