### ISSUE TITLE
'types/node' is not in the npm registry.

### ISSUE THREAD

**Issue by ashikkalavadiya** [arachnys/athenapdf#114]
Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'electron'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 2.6.32-504.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/vagrant/athenapdf/cli
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

**Comment by MrSaints** [comment]
What's your version of Node, and NPM?

```
node --version
npm --version
```

I believe you need to upgrade NPM to 3.x.

**Comment by MrSaints** [comment]
@ashikkalavadiya Is this still an issue? Feel free to re-open the issue if it is.
