### ISSUE TITLE
3.0.0-b on ECS - Unable to contact debugger

### ISSUE THREAD

**Issue by pgrm** [arachnys/athenapdf#119]
When I run version `3.0.0-b` on ECS I see the error 

    Unable to contact debugger at http://localhost:34069/json after 15 seconds, gave up

in sentry. Checking stdout of the container I cannot see anything else, but when I try to run chrome inside the container on ECS I get 

    FATAL:zygote_host_impl_linux.cc(107)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

This is the best I could come up with as a reason for the process failing. Supposedly it's because `userns` isn't enabled? Inspecting the container I can see 

    "UsernsMode": "",

This is my task definition:

    {
      "family": "...",
      "containerDefinitions": [
        {
          "portMappings": [
            {
              "containerPort": 8080,
              "protocol": "tcp"
            }
          ],
          "essential": true,
          "environment": [
            {
              "name": "WEAVER_AUTH_KEY",
              "value": "..."
            },
            {
              "name": "WEAVER_ATHENA_CMD",
              "value": "athenapdf --no-javascript"
            },
            {
              "name": "WEAVER_MAX_WORKERS",
              "value": "10"
            },
            {
              "name": "WEAVER_MAX_CONVERSION_QUEUE",
              "value": "50"
            },
            {
              "name": "WEAVER_WORKER_TIMEOUT",
              "value": "90"
            },
            {
              "name": "WEAVER_CONVERSION_FALLBACK",
              "value": "false"
            },
            {
              "name": "SENTRY_DSN",
              "value": "..."
            }
          ],
          "memoryReservation": 256,
          "name": "pdf-rendering",
          "image": "arachnysdocker/athenapdf-service:3.0.0-b"
        }
      ]
    }

Version `2.9.2` works, but doesn't support the `--no-javascript` which we'll need later on for production. Is somebody already running `3.0.0-b` on ECS? what should I change?

Thanks

**Comment by MrSaints** [comment]
Our demo is running on ECS without any problems. From the looks of it, the only differences between your task definition, and ours is `"privileged": true`. I know it is not ideal, but there is a card for this already (https://github.com/arachnys/athenapdf/projects/1).

**Comment by pgrm** [comment]
Thx, adding those options did the trick. 

One more question, and I don't want to create a new issue for it - IAM roles don't seem to be supported, is there any plan on changing this in the future? Just like the `public-read` ACL actually isn't what we want, we'd rather have a proxy which checks dependencies, ...

**Comment by MrSaints** [comment]
@pgrm That's a really good point. I don't see why not. If you could open an issue on it, I'll be sure to prioritise it.

**Comment by pgrm** [comment]
@MrSaints thanks for your help, I've created the 2 issues about IAM (https://github.com/arachnys/athenapdf/issues/120) and ACLs (https://github.com/arachnys/athenapdf/issues/121) 

Unfortunately, this is probably my first encounter reading go code, so I can't be any more helpful.

**Comment by MrSaints** [comment]
No worries @pgrm. And thank you so much for your contributions 😄

**Comment by MrSaints** [comment]
Fixed in ef264da3dd5394333e0731a73a3b2c0f32b195fa
