### ISSUE TITLE
Make ACL public-read configurable

### ISSUE THREAD

**Issue by pgrm** [arachnys/athenapdf#121]
It would be cool if `public-read` ACL could be turned off either via environment variables (preferable for me since we need to keep it turned off all the time) or at least via query parameters. Currently it's hard coded here:

https://github.com/arachnys/athenapdf/blob/cdp/cmd/weaver/converter/upload_conversion.go#L51

**Comment by MrSaints** [comment]
Whoops. I merged a PR for this in #98 after creating the `cdp` branch. 

https://github.com/arachnys/athenapdf/blob/master/weaver/converter/upload_conversion.go#L62

It should be addressed in the latest version soon.
