### ISSUE TITLE
can I install it locally instead of docker?

### ISSUE THREAD

**Issue by arbabnazar** [arachnys/athenapdf#122]
I know it's not the problem channel to ask but can I install it on the local machine(ubuntu) instead of docker due to some strange requirements. Thanks

**Comment by MrSaints** [comment]
Is this for the CLI or service assembly? It is possible to install it locally, but it will require a bit of manual work to prepare the environment. I recommend looking at the `Dockerfile` to see what is required. You just need to mimic it.

**Comment by MrSaints** [comment]
Let me know if you have any additional questions.

**Comment by arbabnazar** [comment]
@MrSaints can you please point me to the Dockerfile(there are two in the repo) so that I'll start it. Thanks

**Comment by MrSaints** [comment]
@arbabnazar https://github.com/arachnys/athenapdf/blob/master/cli/Dockerfile
