### ISSUE TITLE
Empty PDF when converting using HTTP Post v3

### ISSUE THREAD

**Issue by pgrm** [arachnys/athenapdf#123]
Converting files using HTTP Get works just fine, but when I try to send a file, I only get an empty pdf with 922 bytes rendered.

I tried it in postman, I get `{ "status": "uploaded" }` back from the server. When I have a short glimpse at the file written to the `/tmp` directory I can see that it's the correct content, but still I can't get any.

The url I tried is http://localhost:8080/convert?auth=MY_AUTH&ext=html and the form-data I'm sending has one item with key `file` and element is the attached test.html. Also the generated and empty pdf is attached.

Any ideas what I should change?

[files.zip](https://github.com/arachnys/athenapdf/files/1178307/files.zip)

**Comment by MrSaints** [comment]
If it is possible, can I have a look at the body data you are using (omitting anything confidential)?

**Comment by pgrm** [comment]
I've extracted the postman call and published it as a collection - https://documenter.getpostman.com/view/1567159/athena-pdf-public/6mxaGtt

The curl (which you can see on the website) looks like this:

````
curl --request POST \
  --url 'http://localhost:8080/convert?auth=MY_AUTH&ext=html' \
  --header 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  --form file=undefined
````

and instead of the `undefined` from file, I'm sending the `test.html` file which you can find in [files.zip](https://github.com/arachnys/athenapdf/files/1178307/files.zip) which I already uploaded.

I'm not sure why there is the boundary in the header, I didn't add it explicitly and I can't remove it.

Could you maybe send me a curl command which should work? Than I can try that out - I couldn't find one in this repository.

**Comment by MrSaints** [comment]
I'm getting `{"error":"invalid file provided"}` using a similar request as yours. 

This works though:

```
curl -F file=@index.html http://localhost:8080/convert\?auth\=<AUTH>\&ext\=html
```

**Comment by pgrm** [comment]
The curl command you provided is translated to the same postman script, so probably postman just has issue creating curl commands.

When I try your command, I still only get an empty pdf file and nothing is rendered there. I'm trying this with the image `arachnysdocker/athenapdf-service:3.0.0-b`

**Comment by MrSaints** [comment]
That's interesting, could you try it with `curl` ? Is it perhaps not able to find the HTML file?

**Comment by MrSaints** [comment]
Okay, ignore my previous message. I was able to replicate it on Postman.

**Comment by pgrm** [comment]
I did try it with curl, and I'm getting still the same issue - I redeployed our docker-compose file and switched to `arachnysdocker/athenapdf-service:2.9.2` and now the curl command works - will check if my integration tests and postman also work, but it seems it's a bug with the currently deployed image 3.0.0-b ?

**Comment by pgrm** [comment]
I can confirm, after going down to version 2.9.2 everything works as expected, back to version 3.0.0-b I'm getting empty pdf files rendered

**Comment by MrSaints** [comment]
Thinking about it, yes, I believe this problem is likely due to how local file paths are being handled. 

Unfortunately, I'm not sure if I'm keen on fixing `3.0.0-b` seeing that a lot of changes have been made to the underlying Athena `runner` since then (and we have created a new microservice assembly in the process). 

On that note, I have pushed a new, pre-release of `3.0.0` to Docker Hub which should work with both a `GET`, and a `POST`. The API however, is significantly different _(nothing about it is backwards compatible)_. 

If that is OK, you can give it a shot by pulling `arachnysdocker/athenapdf-service:3`.

Below are some sample cURL requests:

**POST**

```
curl -F file=@index.html -F process='{"conversion": {"mime_type": "text/html"}}' http://localhost:8080/process > test.pdf
```

**GET**

```
curl -X GET http://localhost:8080/process\?uri\=http://www.github.com\&fetcher\=http > test.pdf
```

Let me know if you have any questions.

**Comment by basz** [comment]
how about the auth param? doesn't seem to work

**Comment by MrSaints** [comment]
There shouldn't be any auth in v3 @basz.

**Comment by supermanzer** [comment]
Any ideas why I receive a 404 when running the GET curl request listed above?

**Comment by supermanzer** [comment]
I'm using v3 as a component service in a larger Docker project.  I was running some tests and, while GitHub rendered properly, I got an odd PDF when I ran the cURL request against nytimes.com.
[test.pdf](https://github.com/arachnys/athenapdf/files/1768685/test.pdf)
Any Ideas on how to avoid the lack of styling?

**Comment by kenbolton** [comment]
For those working with the Python `requests` library (including future me) and attempting to POST:

```
weaver_url = 'http://localhost:8080/process'
file_content = open('./path/to/file', 'rb')
files = {
    'file': (file_content),
    'process': (None, '{"conversion": {"mime_type": "text/html"}}'),}
resp = requests.post(weaver_url, files=files)
```

The `None`
