### ISSUE TITLE
Links href outputted additionally in parentheses

### ISSUE THREAD

**Issue by anebi** [arachnys/athenapdf#124]
Hello,

I face the following issue and don't know how to solve it:

Href values of links on pages are directly outputted in pdf next to the link value (no matter if text or image). Is there a way to turn that feature off?

You can see how it looks on attachment:

![athenapdf-links-issue](https://user-images.githubusercontent.com/225278/28718762-032bc496-73b0-11e7-8fd2-8c458cb86e58.png)

**Comment by MrSaints** [comment]
Hi @anebi,

It is not a feature on the side of Athena. It is triggered by the media type being set to `print` rather than `screen`. That is, you will need to change your print-specific styles.

If you are using Athena v3, you can set the media type to `screen` using: `-M="screen"`.
This is not available in `master` or v2 at the moment.

Let me know if that answers your question.

**Comment by anebi** [comment]
Hello,

Thank you very much for your fast reply and detailed explanation. I do run docker version arachnysdocker/athenapdf-service. I am not sure which version is installed on this docker image. athenapdf -V returns empty result.

I will looks for a solution to change the media type.

Thanks again! :)

**Comment by anebi** [comment]
I can see that it is 2.9.2 actually. Is there a v3 docker image?

**Comment by MrSaints** [comment]
Yes, have a look at: https://github.com/arachnys/athenapdf/issues/123#issuecomment-318345714.
There's been a lot of changes (undocumented for now). But, if you are using the service, there is currently no way of setting custom runtime flags.

Alternatively (and maybe simpler), you can just modify your CSS to remove the print-specific styles.
If you use Bootstrap, this is normally shipped with it by default. You might want to generate a version of it that does not contain print styles.

**Comment by anebi** [comment]
Thanks. For now this info is enough. I will take care from that point :)

Best regards,
Ali Nebi
