### ISSUE TITLE
Image compression when generating PDF

### ISSUE THREAD

**Issue by marcushyett** [arachnys/athenapdf#126]
Some of our users generate PDF with lots of images, is there any way we can support generating PDFs with images automatically compressed in them?

**Comment by MrSaints** [comment]
IMHO, my stance is similar to the comment I made here: https://github.com/arachnys/athenapdf/issues/125#issuecomment-319305382.

That is, I think it is out of scope. We could probably bake in a separate API or process stage to do pre- / post-processing (maybe using something like https://github.com/MrSaints/go-ghostscript or https://github.com/MrSaints/go-qpdf for linearization / compression), but I do not seeing that being done any time soon.
