### ISSUE TITLE
Converting page with self-signed certificate

### ISSUE THREAD

**Issue by almini** [arachnys/athenapdf#127]
In v3 I get the following error when trying to convert a page with a self-signed certificate:
```
athenapdf: error: failed to load the page: net::ERR_INSECURE_RESPONSE
```
Unfortunately the option --ignore-certificate-errors does not work in v3. 
In #40 it is mentioned that this issue should be resolved. Can you explain that further?

**Comment by MrSaints** [comment]
Ah yes, I'll probably have to pass it (` --ignore-certificate-errors`) through the runner as well. Thanks for reporting.

**Comment by MrSaints** [comment]
This should now be fixed.

See 45e65b46f960d51e9c9d4554379160f0509db72b for more information.

I'll push it up to Docker Hub shortly.

Thanks for reporting it!
