### ISSUE TITLE
Constantly Receiving 400 Bad Request

### ISSUE THREAD

**Issue by GnrySgtSkitlz** [arachnys/athenapdf#128]
Hi,

Currently I have a HttpClient that I am trying to write a PostAsync for.
Here are some basics I have set:
`private const string _athenaUrl = "http://athenapdf:8080/convert?auth=arachnys-weaver&ext=html";`
`private string _filePath = "/Project/Test.html";`

Here is where I am trying to create the MultipartForm to provide to the AthenaPdf api
`var request = new MultipartFormDataContent();`
`request.Headers.ContentType = new MediaTypeHeaderValue("multipart/form-data");`
`var content = new ByteArrayContent(File.ReadAllBytes(_filePath)); `**--> I think issue is here**
`content.Headers.ContentType = new MediaTypeHeaderValue("text/html");`
`content.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data") { Name ="file", FileName = "test.html"};`
`request.Add(content);`

Here is my PostAsync
`var response = await _client.PostAsync(_athenaUrl, request);`

The reason I have created it this way is that I could get postman to execute this correctly, and even though the code snippet reads of RestClient requests...I believe using a httpclient should work in the same principle...

Any help is greatly appreciated!!

Cheers
Clinton

**Comment by MrSaints** [comment]
Hi Clinton,

When you receive a 400 Bad Request error, what is the exact error message you are receiving? Can you find out?

Thanks!

**Comment by GnrySgtSkitlz** [comment]
Hi MrSaints,

I managed to figure out what was wrong, I had to remove setting the Content-Type as .net already handles this by default as i have specified the types for the objects.

Thanks,
Clinton

**Comment by MrSaints** [comment]
@GnrySgtSkitlz, that's great!

As for your second question, that's not possible at the moment. It is something that you will have to set at runtime. I was considering this in v3, but at the moment, that too is [not configurable](https://github.com/arachnys/athenapdf/blob/v3/pkg/converter/athenapdf/athenapdf.go#L29).
