### ISSUE TITLE
Possible to send multiple files (images, css files)?

### ISSUE THREAD

**Issue by Fuco1** [arachnys/athenapdf#138]
I'm uploading the html file in the `file` form but it requires some additional files like images and styles.  Is there some way to send more than just one file to the server?  I would really like to avoid setting up a http server to serve the page just so it can get rendered.

I'm using athena from a node application which genedates contracts, so I just generate the data, render a handlebars template and then send the result to athena.  Unfortunatelly I haven't found a way to send other files along (I could in theory embed everything in the single html template but that would get unwieldy).

The node code is something lke this

```js
           const buffer = Buffer.from(html);
            buffer['httpVersion'] = true;
            buffer.headers = { 'content-length': html.length }

            const formData = {
                file: {
                    value: buffer,
                    options: {
                        filename: 'input.html',
                        contentType: 'text/html;charset=utf-8',
                    },
                },
            }

            const pdf = await rp({
                method: 'POST',
                uri: config.athenapdf.host + ':' + config.athenapdf.port + "/convert?auth=arachnys-weaver&ext=html",
                formData: formData,
                encoding: null,
            })
```

**Comment by MrSaints** [comment]
Unfortunately, it is not currently supported, and I'm not sure how we can go about supporting something like this - open for ideas (maybe zipped file?).

For the time being, you can resolve your problem by sending a MHTML file or by simply inlining all your assets.

**Comment by Fuco1** [comment]
Yea, the idea of inlining occurred to me right after I opened this issue :blush: I've found this https://github.com/remy/inliner which seems to work and the "packed" html file renders correctly.

I think we can close this and in the future people will just have a reference to a solution.  Probably not worth messing around with zip files.  What do you think?

**Comment by MrSaints** [comment]
Yes, I agree. I'm not too keen in building to address complex workflows. The orchestration of these workflows should live outside of the converter.
