### ISSUE TITLE
There is a difference in the final pdf generated using athenapdf.com and our own docker instance

### ISSUE THREAD

**Issue by aravinthchandramouli** [arachnys/athenapdf#144]
We use the same input html file url in both athenapdf.com and as an input for the docker instance running on our server. We see a lot of difference between the two outputs (especially page margins and paddings). We made sure we use the latest version of athena API. 

Attached the appropriately named generated PDF files from both.

[our-docker-instance-generated.pdf](https://github.com/arachnys/athenapdf/files/1631939/our-docker-instance-generated.pdf)
[athenapdf-com-genarated.pdf](https://github.com/arachnys/athenapdf/files/1631940/athenapdf-com-genarated.pdf)

**Comment by MrSaints** [comment]
Since late last year, we have been trial'ing parts of v3 on our demo website. That is likely to explain the difference.

**Comment by basz** [comment]
On a quick trail run with v3 I noticed that stylesheets werent applies for loading a uri. Is there some additional Param or option I should set?

**Comment by MrSaints** [comment]
@basz They should always load. If it's possible, can I have a look at the HTML for the URI you tried to load? (omit confidential details)

**Comment by basz** [comment]
HI @MrSaints this source https://gist.github.com/basz/67f047443f261d921486e8a5c2f80b6b renders in v2 as https://share.bushbaby.nl/poQrP8Zrtq/ and in v3 as https://share.bushbaby.nl/6LeSPy0Z8f/

**Comment by MrSaints** [comment]
Interesting @basz. Is `/css/admin/reporting.css` accessible ? Also, can you remove `media="screen, print"` (I don't think it'll change anything, but worth trying).

**Comment by MrSaints** [comment]
Silly Q, is the main page / URL showing up in the Apache logs?

**Comment by basz** [comment]
yes, as `"GET /admin/orders/reporting/order-costing?standalone=1&i=11411-13600-18113&sess=xx HTTP/1.1" 200 4636 "-" "Go-http-client/1.1"`

**Comment by MrSaints** [comment]
- Are you using the CLI or the microservice?
- What's the command / configuration you used to start the CLI or the microservice?

**Comment by basz** [comment]
```
dockerun -p 8080:8080 --rm arachnysdocker/athenapdf-service:3 -D
```
then
```
curl -X GET 'http://localhost:8080/process?uri=https%3A%2F%2Flab.sandalinos.nl%3A443%2Fadmin%2Forders%2Freporting%2Forder-costing%3Fstandalone%3D1%26i%3D11411-13600-18113%26sess%3D67xxx&fetcher=http' > test.pdf && open test.pdf 
```

**Comment by MrSaints** [comment]
From the looks of it, it's relying on a HTTP fetcher (the `fetcher=http` bit). So what that means is it will download the HTML for conversion locally. The URL for the stylesheet will not resolve if we are converting locally. You can either change that URL to include your full host or get rid of `fetcher=http`, and set `mime_type=text/html`.

**Comment by basz** [comment]
> mime_type=text/html

yes! awesomeness. thank you!

**Comment by basz** [comment]
No v3 docs yet are there?
