### ISSUE TITLE
v3 CLI for Windows and Linux

### ISSUE THREAD

**Issue by imjustd** [arachnys/athenapdf#149]
I prefer to use CLI and don't want using Docker for generating PDFs. So I'm little lost with the CLI, I just don't know how to make one.

I interested in having Windows CLI, but if that's not possible, how to build a CLI for Linux? A step by step guide is greatly appreciated. Thanks!

**Comment by MrSaints** [comment]
Apologies, this isn't going to be the most detailed guide for Linux @imjustd, but:

1. Install [Go](https://golang.org/)
2. `go install -i github.com/arachnys/athenapdf/tree/v3/cmd/cli`, you should then find it in `$GOPATH/bin`
3. Alternatively, you can navigate to that Go package ($GOPATH/src/...), and execute `go build`

As a prerequisite, install Chromium >= 60 (headless) where you are running your CLI.

Let me know if you have any specific questions.

**Comment by imjustd** [comment]
Thanks! I'll try it out.

**Comment by kissifrot** [comment]
@imjustd How did it go?

**Comment by imjustd** [comment]
@kissifrot I actually decide to use [electron](https://github.com/electron/electron) directly for generating the PDF. See `printToPDF` method here https://electronjs.org/docs/api/web-contents#web-contentsprinttopdf
