### ISSUE TITLE
PDF conversion failed due to an internal server error

### ISSUE THREAD

**Issue by aravinthchandramouli** [arachnys/athenapdf#151]
Unable to convert any url to pdf in the docker service that we have started. Tried restarting the service as well.

**Comment by MrSaints** [comment]
Can you check the Docker logs?

**Comment by aravinthchandramouli** [comment]
The docker service abruptly stopped which is why there was an issue. Will close this issue. But can you tell me where to check the logs for athena?

**Comment by MrSaints** [comment]
There's quite a lot of logging information written to stdout by default, so you can just use `docker logs <container ID>` (the ID can be found in `docker ps`) or depending on how you are running it, it will be sent to the logging driver of your choice.
