### ISSUE TITLE
How to perform batch conversion? (aka one url per line)

### ISSUE THREAD

**Issue by will76** [arachnys/athenapdf#156]
Could not find a way to point to a file containing for example one url per line.

How can we do it?

Thanks

**Comment by MrSaints** [comment]
@will76 That's not currently possible. I can consider it for a feature for v3, but to be honest, I am not too keen on building any sort of complex conversion workflow into the service. I think there are better tools out there to assist with the orchestration. e.g. https://netflix.github.io/conductor/

**Comment by will76** [comment]
@frankh That is exactly the workaround for the lack of this feature.

@MrSaints I'm relatively(not to say noob) new to Docker, Go and this Microservices concept, so I cannot provide any contribution on this. But I mean, this is a piece of software that **must** take an input as argument to run. Performing batch jobs should definitely be a feature.

Anyway, thanks!

**Comment by dbuxton** [comment]
Hmm feels to me that it's not really a "workaround" but more the Unix philosophy of how to compose tools... I'm going to close this, kudos to @frankh for the support.
