### ISSUE TITLE
docker build fails at „Step 5/11 : COPY build/weaver /athenapdf-service/“

### ISSUE THREAD

**Issue by marteb** [arachnys/athenapdf#157]
i’m trying to build a docker container image to deploy it to Amazon ECS, but the docker build command (`docker build -t martineberle/athenapdf-service .`) fails at `Step 5/11 : COPY build/weaver /athenapdf-service/` with this error:

`COPY failed: stat /var/lib/docker/tmp/docker-builder025847287/build/weaver: no such file or directory`

Am i doing something wrong?

**Comment by MrSaints** [comment]
The build for v1/v2 is pretty dated in terms of Docker workflow. 

Give `make buildservice` a try @marteb :)

**Comment by marteb** [comment]
Ok, thanks. That worked.

**Comment by MrSaints** [comment]
Awesome! Apologies for the not-so-straightforward-setup.
