### ISSUE TITLE
Is there any way to add/edit PDFs metadata?

### ISSUE THREAD

**Issue by pheuko** [arachnys/athenapdf#158]
I would like to add an author metadata to generated PDFs, is it possible?

**Comment by MrSaints** [comment]
It is not currently possible. That said, you can do that using GhostScript pretty easily (or even exiftool). 

The converters we currently support, and will be supporting in the future do not have an option to specify the author or other metadata. Introducing metadata will therefore require another stage in the conversion process, and I'd be leaning more towards using a process / workflow manager to handle all that.
