### ISSUE TITLE
break-before/page-break-before CSS rules in V2?

### ISSUE THREAD

**Issue by lougreenwood** [arachnys/athenapdf#174]
Do these rules work in V2? I can't seem to get them to be applied to a block-element.

Perhaps Athena PDF V2 doesn't render as a printed page in electron, so these print-related CSS rules are ignored?

https://developer.mozilla.org/en-US/docs/Web/CSS/break-before
https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before

**Comment by sanohin** [comment]
Fixed in #181

**Comment by sanohin** [comment]
Fixed in #181
