### ISSUE TITLE
The public website isn't working

### ISSUE THREAD

**Issue by jamesefhawkins** [arachnys/athenapdf#201]
http://www.athenapdf.com/ seems to be down.

**Comment by hazzadous** [comment]
Thanks @jamesefhawkins for pointing out, I'll look into this. For the time being I've removed the link from github.

**Comment by Vinq-it-JV** [comment]
Sorry, still not working, live demo link in github.

**Comment by sxiii** [comment]
End of January 2020: website is still down

**Comment by RNogales94** [comment]
April 2020: website is still down
