### ISSUE TITLE
Is there any API documentation?

### ISSUE THREAD

**Issue by lexicalunit** [arachnys/athenapdf#215]
I'm curious about evaluating `weaver` for our use but I don't see any API documentation. How do I find out what endpoints there are? Basic things like that. Do I just need to read the Go code directly to get that kind of information?

**Comment by MrSaints** [comment]
Hey there, this is roughly documented in https://github.com/arachnys/athenapdf/blob/dc33a8ac7f06ed6054f847aff291e489f981ec9a/README.md#microservice

See also https://github.com/arachnys/athenapdf/issues/180

Though it is worth mentioning this project is no longer actively maintained. I would suggest using https://github.com/thecodingmachine/gotenberg which takes some inspiration from this project, and provides much clearer docs.
