### ISSUE TITLE
Can I set delay config when using Weaver?

### ISSUE THREAD

**Issue by cavneb** [arachnys/athenapdf#27]
I need to set a timeout for the Weaver (hosted) version. Do I need to modify the `WEAVER_ATHENA_CMD` command to include the delay?

Thanks for your help!

**Comment by cavneb** [comment]
Answer:

`—env WEAVER_ATHENA_CMD="athenapdf -S -D 20000"`

**Comment by MrSaints** [comment]
Yes. That's _the only way for now_.
