### ISSUE TITLE
S3 configuration to Weaver?

### ISSUE THREAD

**Issue by cavneb** [arachnys/athenapdf#28]
In the Weaver README, it says it can be configured to upload to S3. How can I do this configuration? Thank you for your help!

**Comment by MrSaints** [comment]
My apologies @cavneb. It appears that we've forgotten to document that aspect of it.

You'll just have to pass the S3 details as a query parameter, e.g. `?aws_region=<AWS_REGION>&aws_id=<AWS_ID>&aws_secret=<AWS_SECRET>&s3_bucket=<S3_BUCKET>&s3_key=<S3_KEY>`

Let me know how it goes 👍

**Comment by cavneb** [comment]
Thanks!
