### ISSUE TITLE
"Failed to load: -6" with local file

### ISSUE THREAD

**Issue by cwardzala** [arachnys/athenapdf#33]
```bash
vagrant@mrpdf:/opt/MrPDF/log$ docker run --rm -v $(pwd):/converted/ arachnysdocker/athenapdf athenapdf /tmp/348e3a26fe6c19b7e80e2338c720792e.html
Xlib:  extension "RANDR" missing on display ":99".
Xlib:  extension "RANDR" missing on display ":99".
Failed to load: -6  (file:///tmp/348e3a26fe6c19b7e80e2338c720792e.html)
```

I keep getting this and I am not sure what I am doing wrong?

**Comment by MrSaints** [comment]
`-6` means the file can't be found. I'm guessing your target file `348e3a26fe6c19b7e80e2338c720792e.html` doesn't exist inside `/tmp` ?

**Comment by hazzadous** [comment]
Could it be because the file isn't mounted inside the container?

**Comment by cwardzala** [comment]
I figured out that the way i was mounting the folder and attempting to access files was wrong.
