### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by danielwhatmuff** [arachnys/athenapdf#40]
Is it possible to add a runtime option which allows the conversion of sites using untrusted SSL?

We need to convert some internal facing sites to PDF and the certificates are not trusted.

**Comment by MrSaints** [comment]
Hey @danielwhatmuff, apologies for the tardy response.

We plan on introducing more runtime options, including one for reducing the SSL strictness. I can't confirm when this will be ready, but it is definitely a nice to have feature.

In the code, it's just a matter of setting `TLSClientConfig: &tls.Config{InsecureSkipVerify: true}`.

**Comment by MrSaints** [comment]
This is resolved in v3.
