### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by zohararad** [arachnys/athenapdf#5]
AthenaPDF looks amazing! Can't wait to give it a try, but need to fetch HTML remotely via proxy. Any planned support for this?

**Comment by MrSaints** [comment]
Hey @zohararad, thank you.

Unfortunately, we do not currently have any plans for it, but I think it's worth considering / adding.

**Comment by zohararad** [comment]
@MrSaints glad to hear it. Was trying to figure out where exactly in the code such enhancement should go. If you point me in the right direction, I might be able to add it in the coming week or so

**Comment by MrSaints** [comment]
Apologies for the tardy response @zohararad.

I do believe it can be implemented through Electron's [`session`](https://github.com/electron/electron/blob/master/docs/api/session.md) module. Either that, or through Chrome's [command line switches](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#--proxy-serveraddressport).

**Comment by zohararad** [comment]
@MrSaints no worries. Looks like a good direction. Any chance of pointing me to the right place in athenapdf codebase where Electron is used? Will save me a bit of time looking.

**Comment by MrSaints** [comment]
@zohararad https://github.com/arachnys/athenapdf/blob/master/cli/src/athenapdf.js, it's a bit of a procedural mess ATM, but do bug me if you have any questions.

**Comment by zohararad** [comment]
Great... looking at it now. Thanks!
