### ISSUE TITLE
Stop PDF from writing to file?

### ISSUE THREAD

**Issue by jasonhero** [arachnys/athenapdf#52]
Is there anywhere to not write the output of athenapdf to a file? I'd like to be able to serve the stdout up to a browser and not have to save it somewhere on the machine itself.

**Comment by JD-Robbs** [comment]
Hi @jasonhero, could you share your solution with me, by any chance?

**Comment by MrSaints** [comment]
@JD-Robbs you can pipe to stdout using the `-S` flag.

Example: `athenapdf -S https://www.google.com`

**Comment by JD-Robbs** [comment]
@MrSaints, you're a star — thank you!
