### ISSUE TITLE
question: Running it all inside Electron possible ?

### ISSUE THREAD

**Issue by ghost** [arachnys/athenapdf#55]
In order for weaver to work it has to run in docker right ?
Its essentially running electron in a headless container to get the job done i am guessing.

Its a great design, but I need it to run on Desktops with no Docker or reliance on Server.

Please advise, and i can make the agreed changes if you open to that and its required.

**Comment by MrSaints** [comment]
Hey @gedw99,

What do you mean by on "desktops with no ... reliance on server" ? Can you give an example perhaps?

I can understand the Docker bit, and it is possible to run it without Docker, provided that it is being executed in a graphical environment, and `WEAVER_ATHENA_CMD` is set to the `athenapdf` CLI bin.

If you're referring to running it in a completely headless environment without Docker, and without a virtual display server like `xvfb`, then that is not possible at the moment. It is a [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=546953) constraint that is being worked on as we speak.
