### ISSUE TITLE
Zoom option does not affect output

### ISSUE THREAD

**Issue by blabj** [arachnys/athenapdf#57]
Trying to use the --zoom <factor> CLI option to scale the PDF output, but no matter what I pass as factor, the output is identical.  I've tried 0.1, 0.5, 1.5, 2, 5, 10, 100 and 200 and the output is always the same.  

Version being the "latest" from docker as of today.

**Comment by MrSaints** [comment]
Hi @blabj,

Unfortunately, the `--zoom` option only affects the _scaling factor_ when printing (see https://github.com/arachnys/athenapdf/pull/29, and https://github.com/arachnys/athenapdf/issues/38 for more information). It doesn't _'zoom'_ in the way you'd expect when browsing a web page. Misleading, I know. But it has _no effect_ on the print output besides the aforementioned.

Print _scaling_ is not currently supported in Chromium which is what we are essentially using for conversions (see https://bugs.chromium.org/p/chromium/issues/detail?can=2&start=0&num=100&q=print%20scale&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=96456). 

Nevertheless, it is possible to _zoom_ by setting `zoom: 110%` on the `body` via CSS. I reckon we could do this pretty easily through a plugin. Would something like that help / is it what you're looking for?

Let me know.

Thanks 😄

**Comment by blabj** [comment]
Hi - I was able to use javascript/css to adjust the zoom level, since
its for internal site that I can alter. But yes, a better description of
the option might help others as well. 

Thanks! 

On 2016-07-18 06:15, Ian L. wrote: 

> Hi @blabj [1], 
> 
> Unfortunately, the --zoom option only affects the _scaling factor_ when printing (see #29 [2], and #38 [3] for more information). It doesn't _'zoom'_ in the way you'd expect when browsing a web page. Misleading, I know. But it has _no effect_ on the print output besides the aforementioned. 
> 
> Print _scaling_ is not currently supported in Chromium which is what we are essentially using for conversions (see https://bugs.chromium.org/p/chromium/issues/detail?can=2&start=0&num=100&q=print%20scale&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=96456 [4]). 
> 
> Nevertheless, it is possible to _zoom_ by setting zoom: 110% on the body via CSS. I reckon we could do this pretty easily through a plugin. Would something like that help / is it what you're looking for? 
> 
> Let me know. 
> 
> Thanks 😄 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [5], or mute the thread [6].
 

Links:
------
[1] https://github.com/blabj
[2] https://github.com/arachnys/athenapdf/pull/29
[3] https://github.com/arachnys/athenapdf/issues/38
[4]
https://bugs.chromium.org/p/chromium/issues/detail?can=2&amp;start=0&amp;num=100&amp;q=print%20scale&amp;colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&amp;groupby=&amp;sort=&amp;id=96456
[5]
https://github.com/arachnys/athenapdf/issues/57#issuecomment-233292388
[6]

**Comment by MrSaints** [comment]
I believe this should be _resolved_ in v3.
