### ISSUE TITLE
Loading of Angular Style URL's

### ISSUE THREAD

**Issue by ted-dunstone** [arachnys/athenapdf#58]
Thanks for making a start on a great conversion tool. So far seems to work more consistently on complex web pages than wkhtml2pdf.

I've run into an issue with angular style URLS that have a # in them. To see this in action run a conversion on http://triangular.oxygenna.com/#/dashboards/sales - rather than convert this page it just converts the default page http://triangular.oxygenna.com/. I suspect this will turn out to be an issue for quite a few people.

**Comment by MrSaints** [comment]
Hey @ted-dunstone,

We're glad it's working consistently 😄 

It appears to be converting the correct [Angular] URL on our end. Out of curiosity, are you using the CLI tool or the microservice? If it's the latter, you need to ensure the URL you are passing is URL encoded.

Thanks!
