### ISSUE TITLE
Option for converting from html string in memory?

### ISSUE THREAD

**Issue by fiveohhh** [arachnys/athenapdf#63]
This is more of a question, but not sure where else to ask.  I have a use case where I'm manipulating some html in software and then generating a pdf.  Is there a way to use Athenapdf without having to have either a local file or a public url?

**Comment by MrSaints** [comment]
Duplicate of #13, and fixed by PR #21.

You can pipe the HTML via `stdin`:

    echo "<h1>stdin test</h1>" | docker run -i --rm -v $(pwd):/converted/ arachnysdocker/athenapdf athenapdf -

Let me know if that answers your question :smile:

**Comment by fiveohhh** [comment]
Awesome, thanks for the quick response.  Any chance that this ability exposed via weaver?

**Comment by fiveohhh** [comment]
To be a little more clear of my use case, I'm currently using https://github.com/openlabs/docker-wkhtmltopdf-aas.  I send a request to it with my html and I get the actual pdf back in the response.  I then do some other things and fire the pdf back to the customer.

**Comment by MrSaints** [comment]
@fiveohhh Yes, Weaver has support for `multipart/form-data`. See https://github.com/arachnys/athenapdf/pull/54#issuecomment-230511501.

In the example that I've linked, you can in theory set `input.html` to anything that you want (although, you should probably keep the `.html` extension).

**Comment by fiveohhh** [comment]
Perfect! thanks for the quick help.  My test document looked very promising.  Hopefully the rest will turn out as well.

**Comment by MrSaints** [comment]
Always happy to help @fiveohhh :smile:
 
Let me know if you run into any issues.
