### ISSUE TITLE
Duplication of thead, and other table related issues

### ISSUE THREAD

**Issue by MrSaints** [arachnys/athenapdf#68]
It has come to my attention that the recent upgrade to Electron 1.4.0, and thus, Chrome 53 has resulted in various issues when rendering tables.

Problematic commit: https://github.com/arachnys/athenapdf/commit/462778a70605bc34e3dd5f76dfd605c62d5e0c35

Related upstream issues:
- https://bugs.chromium.org/p/chromium/issues/detail?id=24826
- https://bugs.chromium.org/p/chromium/issues/detail?id=646591

A fix is available in Chromium Canary, but that is unlikely to reach Electron any time soon.

If you are experiencing this issue, the recommendation for Athena is to pin to an older tag / version.

That is, use:

```
athenapdf:2.7.0
athenapdf-service:2.7.0
```

Future upgrade-related releases will always be pinned / tagged for both the cli, and microservice image.

Apologies for this oversight.

**Comment by JD-Robbs** [comment]
I had the same problem and fixed it via CSS in the interim, although that leads to some styling issues in my case. 


      thead {
        display: table-row-group;
      }

So, thanks for posting the solution - I'll pin to that version for a proper fix, in the meantime.

**Comment by sanohin** [comment]
Fixed in #181
