### ISSUE TITLE
Fonts not displaying properly

### ISSUE THREAD

**Issue by rxng** [arachnys/athenapdf#69]
Hi,

Set it all up in a docker environment and working beautifully! However, when the pdf is generated, the letter spacing is really close together... Using Dejavu Sans. Any idea what the issue is?

**Comment by MrSaints** [comment]
Hi @rxng ,

Do you have an example I can look at?

Thanks!

**Comment by rxng** [comment]
Hi @MrSaints 

Thanks for the prompt response - I found the issue and the solution. By default, debian has an issue with the font kerning and thus I needed to get into the docker container and create a file /etc/fonts/conf.d/100-pdfgenerate.conf with the contents here https://wiki.debian.org/Fonts#Subpixel-hinting_and_Font-smoothing.

Also, I have noticed that the pdf size generated by athenapdf is about 3 times larger than wkhtmltopdf (691kb vs 245kb). Is there a reason for this and any way to reduce the size?

Thanks

**Comment by MrSaints** [comment]
Hi again @rxng ,

Thank you so much for identifying the issue, and providing a solution. I've opened a PR to address the problem.

As for the size of the generated PDF, there appears to be several issues filed on that same issue on Chromium:

- https://bugs.chromium.org/p/chromium/issues/detail?id=92304
- https://bugs.chromium.org/p/chromium/issues/detail?id=103602
- https://bugs.chromium.org/p/chromium/issues/detail?id=99125
- https://bugs.chromium.org/p/chromium/issues/detail?id=414976

You might be able to shave a few bytes off the generated PDF by running tools like `qpdf` on it (or even just passing it through GhostScript interpreter). That might be integrated in the future, but there are no plans for it currently.

**Comment by rxng** [comment]
Thanks @MrSaints ! Hopefully you aren't sick of hearing from me. I'm almost finished, I promise :)

Today I used docker-slim to reduce the docker image size after trying to switch to alpine (vs debian) failed. When I did the slimming of the image, weaver works perfect! The http server is started and accepts requests. However, the moment a pdf is requested, this error throws and I am wondering if there is anyway to fix it? Also, when I compiled athenapdf cli on my own local file system, every time I run it directly, it just outputs nothing.... Wonder if I am doing something terribly wrong? Any help would be appreciated, thank you :)

[Worker #0] processing conversion job (pending conversions: 0)
[Worker #4] processing conversion job (pending conversions: 0)
[AthenaPDF] converting to PDF: https://google.com
[AthenaPDF] converting to PDF: https://google.com
captured errors:
Error #01: exit status 1 :

**Comment by MrSaints** [comment]
@rxng , haha don't worry 😄 Happy to help.

From the sounds of it, I think it (the Docker image) doesn't have xvfb installed, and started up. It's required since Athena isn't exactly _headless_.

See: https://github.com/arachnys/athenapdf/blob/master/cli/entrypoint.sh#L6 and https://github.com/arachnys/athenapdf/blob/master/cli/Dockerfile#L9

As for the second problem, I may need more information. How are you compiling it (the command)? And what OS are you on?

Thanks!

**Comment by rxng** [comment]
Hey @MrSaints 

The system I am on is CentOS7 64bit. I'm following these instructions to compile the binary executive.

1. `npm install`
2. `npm run build`
3. Check the `build/` directory for the respective binaries

It all works and the executable gets placed in: 
Packaging app for platform linux x64 using electron v1.4.0
Wrote new app to build/athenapdf-linux-x64

However, when I type in build/athenapdf-linux-x64/athenapdf -S etc etc etc, nothing happens.
There is no output or anything, it is as though I just pressed enter. So I test the image using 
`docker run --rm -v $(pwd):/converted/ arachnysdocker/athenapdf athenapdf --no-cache --margins none url` and confirmed that using docker, the pdf generates.

Next, I docker exec -it bash into the container and run sh entrypoint.sh followed by /athenapdf/athenapdf , but then I also get the same thing - no output, not nothing, just an empty line return. Am I not running athenapdf cmd correctly?

Cheers
R

**Comment by MrSaints** [comment]
@rxng , yea, I'm guessing it's because your CentOS set up does not have a desktop environment / display driver. If you install Xvfb: `yum -y install Xvfb`, and run it with `xvfb-run`, it should work as expected.

It's probably going to be tedious to enter `xvfb-run` every time, so you'll probably want to run it in background (see the links from my earlier comment):

    Xvfb :99 -ac -screen 0 1024x768x24 > /dev/null 2>&1 &
    export DISPLAY=:99

Let me know if that helps.
