### ISSUE TITLE
Custom page size

### ISSUE THREAD

**Issue by fenstrat** [arachnys/athenapdf#75]
The allowed options to --pagesize are fixed at (A3|A4|A5|Legal|Letter|Tabloid). Just wondering if I'm missing something simple to allow a custom page size?

I've tried inline css  `width: 300mm; height: 300mm;` on the html/body/element being rendered, also tried params like `--page-width 300mm` from wkhtmltopdf - all with no luck.

**Comment by MrSaints** [comment]
Yes, the `pagesize` flag was added before support for custom sizes arrived. This definitely needs to be added, but for now, it is not supported.

**Comment by fenstrat** [comment]
Turns out there is a workaround for this available right now. Custom page sizes can be achieved with the use of the [css @page rule](https://developer.mozilla.org/en/docs/Web/CSS/@page). E.g. `<style type="text/css" media="all">@page {size: 300mm 300mm;}`. Big hat tip to @jaymiejones86 for this.

**Comment by MrSaints** [comment]
The page size should be configurable in v3 (https://github.com/arachnys/athenapdf/tree/cdp). But for v2, and below, please refer to @fenstrat's solution :)
