### ISSUE TITLE
Page orientation setup

### ISSUE THREAD

**Issue by Miniwe** [arachnys/athenapdf#83]
From CLI I can change orientation with --no-portrait param
How I can change it from inline call
http://[domain-name]/convert?auth=arachnys-weaver&url=[url]& ... ?

**Comment by robzolkos** [comment]
@Miniwe if you are wanting the orientation to be always landscape for every render you can start the docker container with a `WEAVER_ATHENA_CMD` environment variable

eg `docker run -p 8080:8080 -e WEAVER_ATHENA_CMD='athenapdf --no-portrait' arachysdocker/athenapdf-server`

Then it will add that param always in the service

**Comment by Miniwe** [comment]
the best solution for me has comeset orientation from css rules

`<style type="text/css" media="print"> @page {size: landscape; } </style>`

**Comment by robzolkos** [comment]
@Miniwe same.  I've found that if you can control the css/html output then you will get the best result, and let Athena just render what it gets 👍

**Comment by MrSaints** [comment]
@robzolkos @Miniwe, Yes. Where possible, I strongly recommend using a HTML / CSS solution. They will (mostly) override the actual renderer configuration (see https://github.com/electron/electron/pull/8365). 

Let me know if you have any further questions.
