### ISSUE TITLE
Disable JS

### ISSUE THREAD

**Issue by pgrm** [arachnys/athenapdf#85]
I'd like to use this tool instead of a self built solution based on wkhtmltopdf, however since users can upload custom html, I disabled JS on wkhtmltopdf, I didn't find any option to do this with athenapdf. Is it possible and how could I do it? - Environment variable would be preferred, but I could also set it on every request or extend the docker image.

**Comment by pgrm** [comment]
Ok, after a second look, I guess what I need is 

     javascript: true,
     webSecurity: true,
 
in https://github.com/arachnys/athenapdf/blob/master/cli/src/athenapdf.js#L96

and additionally I'd need to set those flags in the weaver via the `WEAVER_ATHENA_CMD` env var - did I get it right?

Would you welcome a PR to update the athenapdf.js?

**Comment by MrSaints** [comment]
Hi @pgrm,

Yes, unfortunately we do not have any option to disable JS at the moment. We'd most definitely welcome a PR to introduce this. That's (the link) also the appropriate location to set this.

Let me know if you have any questions.

Thanks!

**Comment by pgrm** [comment]
@MrSaints the PR is there, please check if it make sense or comment on it if I missed something :)

**Comment by MrSaints** [comment]
This will be available in v3 (CDP) https://github.com/arachnys/athenapdf/tree/cdp
