### ISSUE TITLE
Webgl support

### ISSUE THREAD

**Issue by richardgill** [arachnys/athenapdf#88]
Hi,

This tool generates by far the best PDFs I've seen out of any tool. Great work!

I'd like to be able to print webgl canvases. Right now I don't think this works: for example if you try converting: http://webglsamples.org/aquarium/aquarium.html. 

<img width="723" alt="screen shot 2017-02-06 at 14 43 06" src="https://cloud.githubusercontent.com/assets/6640874/22651334/9ee8d562-ec7a-11e6-8ddc-e1ae2c89f85a.png">

Do you know if it's possible to add support for this and roughly how it might be done?

**Comment by MrSaints** [comment]
This is resolved by #89. Thanks again @richardgill 😄
