### ISSUE TITLE
Allow weaver to change Athena cmd at runtime - Page orientation

### ISSUE THREAD

**Issue by rcrowe** [arachnys/athenapdf#9]
Currently the athena command is set in the the config file with `WEAVER_ATHENA_CMD`, but this means the command is fixed.

I need to be able to change page orientation & likely other options as parameters to weaver, just like you can with the auth & s3 credentials.

Is this already possible & I've just missed it, or likely something that you would be willing to add?

Thanks for your work on this, really great tool!

**Comment by MrSaints** [comment]
@rcrowe, it is not currently possible, but we do have plans for supporting it (after we figure out what's the best way to achieve it without bloating our source).

Thank you for your kind words, and we're glad you like it! :smile:

**Comment by GotenXiao** [comment]
Perhaps a JSON object to be thrown in like so:
```json
{
  "options": {
    "margins": {
      "top": "30px"
    },
    "orientation": "Portrait"
  },
  "encoding": "base64",
  "payload": "PCFkb2N0eXBlIGh0bWw+PGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiPjx0aXRsZT5leGFtcGxlLmNvbTwvdGl0bGU+PC9oZWFkPjxib2R5PjxoMT5leGFtcGxlPC9oMT48cD5sb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldDwvcD48L2JvZHk+PC9odG1sPg=="
}
```

This would then enable a fellow webservice to flexibly produce PDF files without having to have a fleet of separately configured weaver instances.

**Comment by mgladdish** [comment]
This is a biggie for us. Having to have dedicated containers running for different args is overkill.

**Comment by MrSaints** [comment]
Sorry I haven't updated this. But, the good news is version 3 should be able to handle most common options (see https://github.com/arachnys/athenapdf/blob/cdp/pkg/proto/conversion.proto). The CLI, and the service will share the exact same conversion options, with room for including more.
