### ISSUE TITLE
Monitor and restart Xvfb

### ISSUE THREAD

**Issue by lanceulmer** [arachnys/athenapdf#90]
I've been using athenapdf for about a month now in a production app and roughly once a week the Xvfb instance dies in the weaver container and we have to restart it. We get a general error message: "PDF conversion failed due to an internal server error". It would really be helpful if the Xvfb process was monitored automatically to keep it alive.

**Comment by MrSaints** [comment]
That's interesting. We've been running ours for months, and we've yet to come across this problem. But considering that there's no supervisor in place, it is definitely a possibility. I'm quite interested to know what may cause it to crash.

**Comment by MrSaints** [comment]
`Xvfb` will no longer be required in v3 as we are going completely headless (https://github.com/arachnys/athenapdf/tree/cdp).
