### ISSUE TITLE
Cookie support

### ISSUE THREAD

**Issue by funsim** [arachnys/athenapdf#91]
wkhtmltopdf has a "--cookie" option, which is very usefull to convert pages that are part of a user session.

It would be great to have the same option also for athenapdf.

**Comment by RoanBrand** [comment]
+1

**Comment by borkdude** [comment]
+1

**Comment by MrSaints** [comment]
This will be available in v3 (https://github.com/arachnys/athenapdf/tree/cdp). `--cookie-jar` however, is not supported.

**Comment by thaoms** [comment]
Is this supported by now?
