### ISSUE TITLE
Upgrade to latest electron

### ISSUE THREAD

**Issue by F21** [arachnys/athenapdf#92]
The latest version of electron is 1.6.1. The project currently uses 1.4.0, so it would be nice if electron can be bumped! 😄

**Comment by MrSaints** [comment]
In the spirit of open source, would you by any chance be keen on opening a PR for this? 😄 

If not, I'm happy to open it to the general public (upgrading should be something along the lines of : https://github.com/arachnys/athenapdf/commit/462778a70605bc34e3dd5f76dfd605c62d5e0c35).

**Comment by F21** [comment]
I don't haven't used nodejs too much, but that looks simple enough! Should I also bump the version number or leave it as is?

**Comment by MrSaints** [comment]
@F21, yes, if you can, let's bump instances of `2.8.0` to `2.9.0` as well 😄 Thanks!

**Comment by F21** [comment]
@MrSaints Done and squashed! 😄
