### ISSUE TITLE
(weaver) Renderer Process Crashes when trying to convert some web pages 

### ISSUE THREAD

**Issue by nootanghimire** [arachnys/athenapdf#95]
This happens when I try to convert  `blog.arachnys.com` to a PDF, this has not happened when converting other web pages.  

The error might be related to libudev . The log in the console is pasted below

````

[Worker #3] processing conversion job (pending conversions: 0)
[AthenaPDF] converting to PDF: http://blog.arachnys.com/
captured errors:
Error #01: exit status 1 : Xlib:  extension "RANDR" missing on display ":99".
Xlib:  extension "RANDR" missing on display ":99".
libudev: udev_has_devtmpfs: name_to_handle_at on /dev: Operation not permitted
The renderer process has crashed.

````

I tried adding  `--security-opt seccomp=unconfined` to the docker run command, but this only removed the `libudev: udev ...` error. The response is still json encoded and says something along the lines of "Internal Error"

**Comment by MrSaints** [comment]
Hi @nootanghimire, can you try it with 2.7.1?

**Comment by nootanghimire** [comment]
@MrSaints Sorry, but I didn't quite get you - Which application's version are you referring to by 2.7.1?

**Comment by MrSaints** [comment]
@nootanghimire Does it work with Docker `arachnysdocker/athenapdf:2.7.1`?

**Comment by MrSaints** [comment]
I see, it must be an issue with Electron. I'll investigate further.

**Comment by nootanghimire** [comment]
Thanks. 

I was also curious about another thing. This might not be a right place to ask, but since I don't see any other place to communicate, 

Why do you suggest to use pipe-and-redirect `|>` instead of plain redirect `>` ?

I was curious because even in 2.7.1 , the conversion fails (interestingly, only for blog.arachnys.com) when the pipe is omitted.

**Comment by MrSaints** [comment]
@nootanghimire I can't remember exactly why I suggested a pipe-and-redirect versus a plain redirect, so that will require some investigation. But, I've had a look at the latest Electron, and the crashing still seems to be a problem. I reckon it's a problem with our blog specifically because of the large image, and OOM. I know this was a problem with Electron at one point.

**Comment by MrSaints** [comment]
@nootanghimire I've filed an issue on Electron: https://github.com/electron/electron/issues/9093

For now, if you want to use the latest version, mount `/dev/shm` or start the container using `--shm-size="2g"` after `docker run` to give it a larger shared memory size.

**Comment by nootanghimire** [comment]
Thanks. :+1:

**Comment by MrSaints** [comment]
The issue was closed upstream as:

> It is probably because Chromium did some change that require a larger shared memory, while we would like to fix this, I'm afraid this is how Chromium works fundamentally and we are unable to work around on Electron's side.

Seeing as it is no longer a problem when using headless Chromium (see https://github.com/arachnys/athenapdf/tree/cdp). I'm going to close this.
