### ISSUE TITLE
Allow override of acl for s3 uploads

### ISSUE THREAD

**Issue by himangshuj** [arachnys/athenapdf#98]
Currently all pdfs generated by athena and uploaded to s3 are public by default. I have a use case where we want to define our own acls for uploaded files. Is there any plan to fix this issue?

**Comment by k13gomez** [comment]
I've created #97 to support this feature, also to allow the service to work with credentials provider chain instead of only static credentials for aws s3 upload.

**Comment by MrSaints** [comment]
That does sound ideal. We're open to having a PR for this @k13gomez @himangshuj 👍 Let me know how it goes, and if you have any questions.

**Comment by k13gomez** [comment]
Hi @MrSaints, take a look at PR #97 https://github.com/arachnys/athenapdf/pull/97 it already has the requested features and its passing all tests.

**Comment by MrSaints** [comment]
This is now merged in, and it should be available in `latest` shortly.
